import crypto from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { checkRateLimit, clientAddress, rateLimitHeaders, rateLimits } from "@/lib/rate-limit";

const input=z.object({token:z.string().min(32),startsAt:z.coerce.date()});
const hash=(value:string)=>crypto.createHash("sha256").update(value).digest("hex");
export async function PATCH(request:Request,{params}:{params:Promise<{bookingRef:string}>}){const limit=checkRateLimit("booking-manage",clientAddress(request.headers),rateLimits.bookingManage);if(!limit.allowed)return NextResponse.json({code:"RATE_LIMITED"},{status:429,headers:rateLimitHeaders(limit)});try{const {bookingRef}=await params;const {token,startsAt}=input.parse(await request.json());const appointment=await prisma.appointment.findFirst({where:{bookingRef,manageTokenHash:hash(token),status:{in:["PENDING","CONFIRMED"]}},include:{salon:true,service:true}});if(!appointment)throw new Error("BOOKING_NOT_FOUND");if(appointment.startsAt.getTime()-Date.now()<appointment.salon.cancellationHours*3600000)throw new Error("RESCHEDULE_WINDOW_CLOSED");if(startsAt.getTime()<Date.now()+appointment.salon.bookingLeadMinutes*60000)throw new Error("BOOKING_LEAD_TIME");const endsAt=new Date(startsAt.getTime()+appointment.service.durationMinutes*60000);const blockedEndTime=new Date(endsAt.getTime()+appointment.service.bufferMinutes*60000);const conflict=await prisma.appointment.findFirst({where:{id:{not:appointment.id},providerId:appointment.providerId,status:{in:["PENDING","CONFIRMED","NEEDS_REASSIGNMENT"]},startsAt:{lt:blockedEndTime},blockedEndTime:{gt:startsAt}}});if(conflict)throw new Error("DOUBLE_BOOKING_CONFLICT");const nextToken=crypto.randomBytes(32).toString("base64url");await prisma.$transaction([prisma.appointment.update({where:{id:appointment.id},data:{startsAt,endsAt,blockedEndTime,manageTokenHash:hash(nextToken),status:"PENDING"}}),prisma.auditLog.create({data:{salonId:appointment.salonId,action:"APPOINTMENT_RESCHEDULED_BY_CUSTOMER",targetType:"Appointment",targetId:appointment.id}})]);return NextResponse.json({ok:true,token:nextToken},{headers:rateLimitHeaders(limit)})}catch(error){return NextResponse.json({code:error instanceof Error?error.message:"RESCHEDULE_FAILED"},{status:400,headers:rateLimitHeaders(limit)})}}
