"use client";

import { useEffect, useId, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { dateLabelFromKey, dateTime, timeOnly } from "@/lib/format";

type BookingActionsProps = { bookingRef:string; token:string; providerId:string; serviceId:string; salonName:string; serviceName:string; providerName:string; startsAt:string; status:string };
type Dialog = "cancel" | "reschedule" | null;
const today=()=>new Date().toISOString().slice(0,10);

/** The management token is never rendered: it is sent only to same-origin booking routes. */
export function CustomerBookingActions(props:BookingActionsProps){
 const router=useRouter(),headingId=useId();
 const [dialog,setDialog]=useState<Dialog>(null),[date,setDate]=useState(""),[slots,setSlots]=useState<string[]>([]),[selectedSlot,setSelectedSlot]=useState("");
 const [availability,setAvailability]=useState<"idle"|"loading"|"error"|"empty"|"ready">("idle");
 const [message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null),[pending,setPending]=useState(false);
 const editable=props.status==="PENDING"||props.status==="CONFIRMED";
 const current=useMemo(()=>new Date(props.startsAt),[props.startsAt]);
 useEffect(()=>{if(!date||dialog!=="reschedule")return;const controller=new AbortController();setAvailability("loading");setSelectedSlot("");fetch(`/api/availability?providerId=${encodeURIComponent(props.providerId)}&serviceId=${encodeURIComponent(props.serviceId)}&date=${date}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error("availability");const body=await response.json() as {slots?:string[]};const next=body.slots??[];setSlots(next);setAvailability(next.length?"ready":"empty")}).catch(error=>{if(error?.name!=="AbortError"){setSlots([]);setAvailability("error")}});return()=>controller.abort()},[date,dialog,props.providerId,props.serviceId]);
 function close(){if(!pending){setDialog(null);setSelectedSlot("")}}
 async function cancel(){setPending(true);setMessage(null);try{const response=await fetch(`/api/bookings/${props.bookingRef}/cancel`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({token:props.token})});if(!response.ok)throw Error();setDialog(null);setMessage({type:"success",text:"Rezervasiyanız ləğv edildi."});router.refresh()}catch{setMessage({type:"error",text:"Ləğv mümkün olmadı. Zəhmət olmasa yenidən cəhd edin."})}finally{setPending(false)}}
 async function reschedule(){if(!selectedSlot)return;setPending(true);setMessage(null);try{const response=await fetch(`/api/bookings/${props.bookingRef}/reschedule`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({token:props.token,startsAt:selectedSlot})});const body=await response.json() as {token?:string;code?:string};if(!response.ok||!body.token){const errors:Record<string,string>={RESCHEDULE_WINDOW_CLOSED:"Dəyişiklik üçün icazə verilən vaxt bitib.",DOUBLE_BOOKING_CONFLICT:"Bu vaxt artıq tutulub. Başqa saat seçin.",BOOKING_LEAD_TIME:"Bu vaxt üçün kifayət qədər öncədən xəbərdarlıq yoxdur."};throw Error(errors[body.code??""]??"Rezervasiyanı dəyişmək mümkün olmadı.")}setDialog(null);setMessage({type:"success",text:"Yeni vaxtınız təsdiqləndi. Rezervasiya yenidən gözləmədədir."});router.replace(`/confirm/${props.bookingRef}?token=${encodeURIComponent(body.token)}`);router.refresh()}catch(error){setMessage({type:"error",text:error instanceof Error?error.message:"Rezervasiyanı dəyişmək mümkün olmadı."})}finally{setPending(false)}}
 return <section className="booking-manage" aria-labelledby={headingId}><div className="manage-heading"><div><p className="eyebrow">TƏHLÜKƏSİZ İDARƏETMƏ</p><h2 id={headingId}>Rezervasiyanızı idarə edin</h2></div><span className="manage-lock" aria-label="Təhlükəsiz keçid">⌁</span></div><p className="muted manage-copy">Bu keçid yalnız sizin rezervasiyanıza aiddir. Dəyişiklik etdikdə yeni təhlükəsiz keçid yaradılır.</p>{message&&<p className={`feedback ${message.type}`} role="status">{message.text}</p>}{!editable?<p className="notice">Bu rezervasiyanın statusu dəyişdirilə bilməz.</p>:<div className="manage-actions"><button type="button" className="button" onClick={()=>{setMessage(null);setDialog("reschedule")}}>Vaxtı dəyiş</button><button type="button" className="button secondary danger-button" onClick={()=>{setMessage(null);setDialog("cancel")}}>Rezervasiyanı ləğv et</button></div>}
 {dialog==="cancel"&&<div className="modal-layer" role="presentation" onMouseDown={close}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="cancel-title" onMouseDown={event=>event.stopPropagation()}><p className="eyebrow">TƏSDİQ TƏLƏB OLUNUR</p><h2 id="cancel-title">Rezervasiyanı ləğv edirsiniz?</h2><p className="muted">{props.salonName} üçün {props.serviceName} rezervasiyanız ləğv ediləcək. Bu əməliyyatı geri qaytarmaq olmur.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={close} disabled={pending}>Geri qayıt</button><button type="button" className="button destructive" onClick={cancel} disabled={pending}>{pending?"Ləğv edilir…":"Bəli, ləğv et"}</button></div></section></div>}
 {dialog==="reschedule"&&<div className="modal-layer" role="presentation" onMouseDown={close}><section className="modal-card reschedule-modal" role="dialog" aria-modal="true" aria-labelledby="reschedule-title" onMouseDown={event=>event.stopPropagation()}><div className="modal-topline"><div><p className="eyebrow">YENİ VAXT SEÇİN</p><h2 id="reschedule-title">Rezervasiyanı dəyiş</h2></div><button type="button" className="close-modal" aria-label="Bağla" onClick={close} disabled={pending}>×</button></div><div className="current-time"><span>Hazırkı vaxt</span><strong>{dateTime(current)}</strong><small>{props.providerName} · {props.serviceName}</small></div><div className="field"><label htmlFor="reschedule-date">Yeni tarix</label><input id="reschedule-date" type="date" min={today()} value={date} onChange={event=>setDate(event.target.value)}/></div><div className="slot-area" aria-live="polite">{!date&&<p className="slot-placeholder">Əvvəlcə tarix seçin, sonra mövcud vaxtları göstərəcəyik.</p>}{availability==="loading"&&<p className="slot-placeholder">Boş vaxtlar yoxlanılır…</p>}{availability==="error"&&<p className="feedback error" role="alert">Vaxtları yükləmək alınmadı. İnternet bağlantınızı yoxlayıb yenidən cəhd edin.</p>}{availability==="empty"&&<p className="slot-placeholder">{dateLabelFromKey(date)} üçün boş vaxt yoxdur. Başqa tarix seçin.</p>}{availability==="ready"&&<><p className="slot-label">{dateLabelFromKey(date)} üçün mövcud vaxtlar</p><div className="slots reschedule-slots">{slots.map(value=><button type="button" aria-pressed={selectedSlot===value} className="slot" onClick={()=>setSelectedSlot(value)} key={value}>{timeOnly(value)}</button>)}</div></>}</div><div className="modal-actions"><button type="button" className="button secondary" onClick={close} disabled={pending}>İmtina et</button><button type="button" className="button" onClick={reschedule} disabled={!selectedSlot||pending}>{pending?"Yadda saxlanır…":"Yeni vaxtı təsdiqlə"}</button></div></section></div>}</section>
}
